pool:
  name: Azure Pipelines
  demands:
  - java
  - npm

#Your build pipeline references an undefined variable named ‘Junior-repo’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Junior-repo’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Junior-repo’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: '$(Build.SourcesDirectory)'
    verbose: false

- task: RaulARuiz.angular-cli-1.angular-cli-build-task.AngularCLI@0
  displayName: 'ng build'
  inputs:
    project: '$(Build.SourcesDirectory)'
    arguments: '--base-href /$(Junior-repo)/'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.binariesdirectory)\binaries\'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*'
    TargetFolder: '$(build.binariesdirectory)\binaries'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.binariesdirectory)\binaries'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*'
    TargetFolder: '$(build.binariesdirectory)\binaries'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
