pool:
  name: Azure Pipelines
  demands:
  - java
  - npm

#Your build pipeline references an undefined variable named ‘Junior-repo’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Junior-repo’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Junior-repo’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'Sonar-Cloud'
    organization: nhlanhla
    scannerMode: CLI
    configMode: manual
    cliProjectKey: '$(Junior-repo)'
    cliProjectName: '$(Junior-repo)'
    cliSources: '$(Build.SourcesDirectory)'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: '$(Build.SourcesDirectory)'
    verbose: false

- task: RaulARuiz.angular-cli-1.angular-cli-build-task.AngularCLI@0
  displayName: 'ng build'
  inputs:
    project: '$(Build.SourcesDirectory)'
    arguments: '--base-href /$(Junior-repo)/'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.binariesdirectory)\binaries\'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*'
    TargetFolder: '$(build.binariesdirectory)\binaries'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.binariesdirectory)\binaries'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*'
    TargetFolder: '$(build.binariesdirectory)\binaries'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
